// --------------------------------------------
// THIS FILE IS AUTOGENERATED, DO NOT CHANGE IT
// --------------------------------------------

package main

import (
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

var logger *zap.SugaredLogger

func init() {
	l, _ := zap.NewProduction()
	defer l.Sync()
	logger = l.Sugar()
}

func main() {
	r := gin.Default()
    
	r.POST("/", func(c *gin.Context) {
        
        c.Data(201, "application/json", []byte("{  'id': '1',  'title': 'Blue Train',  'artist': 'John Coltrane',  'price': 56.99}"))
	})
    
	r.GET("/albums", func(c *gin.Context) {
        
        c.Writer.Header().Set("Accept-Encoding", "*")
        
        c.Data(200, "application/json", []byte("[    {      'id': '1',      'title': 'Blue Train',      'artist': 'John Coltrane',      'price': 56.99    },    {      'id': '2',      'title': 'Jeru',      'artist': 'Gerry Mulligan',      'price': 17.99    },    {      'id': '3',      'title': 'Sarah Vaughan and Clifford Brown',      'artist': 'Sarah Vaughan',      'price': 39.99    }]"))
	})
    
	r.GET("/albums/:id", func(c *gin.Context) {
        
        c.Data(200, "application/json", []byte("{'id': '1', 'title': 'Blue Train', 'artist': 'John Coltrane', 'price': 56.99}"))
	})
    
	logger.Fatalln(r.Run("0.0.0.0:8000"))
}
